# Form implementation generated from reading ui file 'designer\form.ui'
#
# Created by: PyQt6 UI code generator 6.2.3
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(400, 300)
        self.verticalLayout = QtWidgets.QVBoxLayout(Dialog)
        self.verticalLayout.setObjectName("verticalLayout")
        self.icon = QtWidgets.QLabel(Dialog)
        self.icon.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.icon.setObjectName("icon")
        self.verticalLayout.addWidget(self.icon)
        self.formLayout = QtWidgets.QFormLayout()
        self.formLayout.setObjectName("formLayout")
        self.label = QtWidgets.QLabel(Dialog)
        self.label.setObjectName("label")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.ItemRole.LabelRole, self.label)
        self.wordFieldComboBox = QtWidgets.QComboBox(Dialog)
        self.wordFieldComboBox.setObjectName("wordFieldComboBox")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.ItemRole.FieldRole, self.wordFieldComboBox)
        self.label_2 = QtWidgets.QLabel(Dialog)
        self.label_2.setObjectName("label_2")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.ItemRole.LabelRole, self.label_2)
        self.definitionFieldComboBox = QtWidgets.QComboBox(Dialog)
        self.definitionFieldComboBox.setObjectName("definitionFieldComboBox")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.ItemRole.FieldRole, self.definitionFieldComboBox)
        self.label_3 = QtWidgets.QLabel(Dialog)
        self.label_3.setObjectName("label_3")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.ItemRole.LabelRole, self.label_3)
        self.sentenceFieldComboBox = QtWidgets.QComboBox(Dialog)
        self.sentenceFieldComboBox.setObjectName("sentenceFieldComboBox")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.ItemRole.FieldRole, self.sentenceFieldComboBox)
        self.label_4 = QtWidgets.QLabel(Dialog)
        self.label_4.setObjectName("label_4")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.ItemRole.LabelRole, self.label_4)
        self.audioFieldComboBox = QtWidgets.QComboBox(Dialog)
        self.audioFieldComboBox.setObjectName("audioFieldComboBox")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.ItemRole.FieldRole, self.audioFieldComboBox)
        self.verticalLayout.addLayout(self.formLayout)
        self.addButton = QtWidgets.QPushButton(Dialog)
        self.addButton.setDefault(True)
        self.addButton.setObjectName("addButton")
        self.verticalLayout.addWidget(self.addButton)

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        self.icon.setText(_translate("Dialog", "TextLabel"))
        self.label.setText(_translate("Dialog", "Word Field"))
        self.label_2.setText(_translate("Dialog", "Definition Field"))
        self.label_3.setText(_translate("Dialog", "Sentence Field"))
        self.label_4.setText(_translate("Dialog", "Audio Field"))
        self.addButton.setText(_translate("Dialog", "Add"))
